os: linux
dist: trusty
sudo: required
language: python
python:
  - "2.7"
  - "3.6"

install:
  - ./.travis/install.sh

script:
  - ./.travis/build.sh

cache:
  - directories:
    - $HOME/.build_cache
    - $HOME/.ccache

env:
  global:
    - PB_VERSION=2.6.1
  matrix:
    - ONNX_ML=false USE_NINJA=false
    - ONNX_ML=false USE_NINJA=true
    - ONNX_ML=true USE_NINJA=false
    - ONNX_ML=true USE_NINJA=true